package com.github.tarsa.tarsalzp.gui;

import javax.swing.JFileChooser;

/**
 *
 * @author Piotr Tarsa
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -3240444466539184363L;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionButtonGroup = new javax.swing.ButtonGroup();
        optionsBean = new com.github.tarsa.tarsalzp.gui.OptionsBean();
        actionBean = new com.github.tarsa.tarsalzp.gui.ActionBean();
        filenamesPanel = new javax.swing.JPanel();
        inputFileLabel = new javax.swing.JLabel();
        outputFileLabel = new javax.swing.JLabel();
        inputPathTextField = new javax.swing.JTextField();
        outputPathTextField = new javax.swing.JTextField();
        inputFileChooseButton = new javax.swing.JButton();
        outputFileChooseButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        optionsPanel = new javax.swing.JPanel();
        lzpLowContextLengthLabel = new javax.swing.JLabel();
        lzpLowMaskSizeLabel = new javax.swing.JLabel();
        lzpHighContextLengthLabel = new javax.swing.JLabel();
        lzpHighMaskSizeLabel = new javax.swing.JLabel();
        lzpLowContextLengthSpinner = new javax.swing.JSpinner();
        lzpLowMaskSizeSpinner = new javax.swing.JSpinner();
        lzpHighContextLengthSpinner = new javax.swing.JSpinner();
        lzpHighMaskSizeSpinner = new javax.swing.JSpinner();
        ppmOrderLabel = new javax.swing.JLabel();
        ppmInitLabel = new javax.swing.JLabel();
        ppmStepLabel = new javax.swing.JLabel();
        ppmLimitLabel = new javax.swing.JLabel();
        ppmOrderSpinner = new javax.swing.JSpinner();
        ppmInitSpinner = new javax.swing.JSpinner();
        ppmStepSpinner = new javax.swing.JSpinner();
        ppmLimitSpinner = new javax.swing.JSpinner();
        actionPanel = new javax.swing.JPanel();
        actionSelectionPanel = new javax.swing.JPanel();
        encodeRadioButton = new javax.swing.JRadioButton();
        decodeRadioButton = new javax.swing.JRadioButton();
        showDetailsRadioButton = new javax.swing.JRadioButton();
        actionButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        actionBean.setOptionsBean(optionsBean);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        filenamesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Files"));

        inputFileLabel.setText("Input file");

        outputFileLabel.setText("Output file");

        inputPathTextField.setText("Enter path to input file here");

        outputPathTextField.setText("Enter path to output file here");

        inputFileChooseButton.setText("File Chooser");
        inputFileChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileChooseButtonActionPerformed(evt);
            }
        });

        outputFileChooseButton.setText("File Chooser");
        outputFileChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileChooseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filenamesPanelLayout = new javax.swing.GroupLayout(filenamesPanel);
        filenamesPanel.setLayout(filenamesPanelLayout);
        filenamesPanelLayout.setHorizontalGroup(
            filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filenamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputFileLabel)
                    .addComponent(inputFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPathTextField)
                    .addComponent(outputPathTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputFileChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(outputFileChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        filenamesPanelLayout.setVerticalGroup(
            filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filenamesPanelLayout.createSequentialGroup()
                .addGroup(filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileChooseButton)
                    .addComponent(inputFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filenamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel)
                    .addComponent(outputPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileChooseButton)))
        );

        optionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        lzpLowContextLengthLabel.setText("LZP Low Context Length");

        lzpLowMaskSizeLabel.setText("LZP Low Mask Size");

        lzpHighContextLengthLabel.setText("LZP High Context Length");

        lzpHighMaskSizeLabel.setText("LZP High Mask Size");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${lzpLowContextLength}"), lzpLowContextLengthSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"), "");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${lzpLowMaskSize}"), lzpLowMaskSizeSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${lzpHighContextLength}"), lzpHighContextLengthSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${lzpHighMaskSize}"), lzpHighMaskSizeSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        ppmOrderLabel.setText("PPM Order");

        ppmInitLabel.setText("PPM Init");

        ppmStepLabel.setText("PPM Step");

        ppmLimitLabel.setText("PPM Limit");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${ppmOrder}"), ppmOrderSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${ppmInit}"), ppmInitSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${ppmStep}"), ppmStepSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optionsBean, org.jdesktop.beansbinding.ELProperty.create("${ppmLimit}"), ppmLimitSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lzpLowContextLengthLabel)
                    .addComponent(lzpLowMaskSizeLabel)
                    .addComponent(lzpHighContextLengthLabel)
                    .addComponent(lzpHighMaskSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lzpHighMaskSizeSpinner)
                    .addComponent(lzpHighContextLengthSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lzpLowMaskSizeSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lzpLowContextLengthSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppmInitLabel)
                    .addComponent(ppmOrderLabel)
                    .addComponent(ppmStepLabel)
                    .addComponent(ppmLimitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ppmLimitSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(ppmStepSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(ppmInitSpinner)
                    .addComponent(ppmOrderSpinner))
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lzpLowContextLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppmOrderLabel)
                    .addComponent(ppmOrderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lzpLowContextLengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lzpLowMaskSizeLabel)
                    .addComponent(lzpLowMaskSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppmInitLabel)
                    .addComponent(ppmInitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lzpHighContextLengthLabel)
                    .addComponent(lzpHighContextLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppmStepLabel)
                    .addComponent(ppmStepSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lzpHighMaskSizeLabel)
                    .addComponent(lzpHighMaskSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppmLimitLabel)
                    .addComponent(ppmLimitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        actionSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        actionButtonGroup.add(encodeRadioButton);
        encodeRadioButton.setText("Encode input file to output file");
        encodeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeRadioButtonActionPerformed(evt);
            }
        });

        actionButtonGroup.add(decodeRadioButton);
        decodeRadioButton.setText("Decode input file to output file");
        decodeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeRadioButtonActionPerformed(evt);
            }
        });

        actionButtonGroup.add(showDetailsRadioButton);
        showDetailsRadioButton.setText("Show input file compression options");
        showDetailsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionSelectionPanelLayout = new javax.swing.GroupLayout(actionSelectionPanel);
        actionSelectionPanel.setLayout(actionSelectionPanelLayout);
        actionSelectionPanelLayout.setHorizontalGroup(
            actionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encodeRadioButton)
                    .addComponent(decodeRadioButton)
                    .addComponent(showDetailsRadioButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        actionSelectionPanelLayout.setVerticalGroup(
            actionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionSelectionPanelLayout.createSequentialGroup()
                .addComponent(encodeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decodeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDetailsRadioButton))
        );

        actionButton.setFont(actionButton.getFont().deriveFont(actionButton.getFont().getSize()+5f));
        actionButton.setText("Do it!");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, actionBean, org.jdesktop.beansbinding.ELProperty.create("${valid}"), actionButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addComponent(actionSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actionSelectionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Theme");
        menuBar.add(jMenu1);

        jMenu2.setText("About");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filenamesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filenamesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFileChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileChooseButtonActionPerformed
        final JFileChooser chooser = new JFileChooser(
                inputPathTextField.getText());
        chooser.setMultiSelectionEnabled(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            inputPathTextField.setText(
                    chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_inputFileChooseButtonActionPerformed

    private void outputFileChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileChooseButtonActionPerformed
        final JFileChooser chooser = new JFileChooser(
                outputPathTextField.getText());
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            outputPathTextField.setText(
                    chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_outputFileChooseButtonActionPerformed

    private void encodeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encodeRadioButtonActionPerformed
        actionBean.setAction(ActionBean.Action.Encode);
    }//GEN-LAST:event_encodeRadioButtonActionPerformed

    private void decodeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decodeRadioButtonActionPerformed
        actionBean.setAction(ActionBean.Action.Decode);
    }//GEN-LAST:event_decodeRadioButtonActionPerformed

    private void showDetailsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsRadioButtonActionPerformed
        actionBean.setAction(ActionBean.Action.ShowOptions);
    }//GEN-LAST:event_showDetailsRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.tarsa.tarsalzp.gui.ActionBean actionBean;
    private javax.swing.JButton actionButton;
    private javax.swing.ButtonGroup actionButtonGroup;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel actionSelectionPanel;
    private javax.swing.JRadioButton decodeRadioButton;
    private javax.swing.JRadioButton encodeRadioButton;
    private javax.swing.JPanel filenamesPanel;
    private javax.swing.JButton inputFileChooseButton;
    private javax.swing.JLabel inputFileLabel;
    private javax.swing.JTextField inputPathTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lzpHighContextLengthLabel;
    private javax.swing.JSpinner lzpHighContextLengthSpinner;
    private javax.swing.JLabel lzpHighMaskSizeLabel;
    private javax.swing.JSpinner lzpHighMaskSizeSpinner;
    private javax.swing.JLabel lzpLowContextLengthLabel;
    private javax.swing.JSpinner lzpLowContextLengthSpinner;
    private javax.swing.JLabel lzpLowMaskSizeLabel;
    private javax.swing.JSpinner lzpLowMaskSizeSpinner;
    private javax.swing.JMenuBar menuBar;
    private com.github.tarsa.tarsalzp.gui.OptionsBean optionsBean;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton outputFileChooseButton;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JTextField outputPathTextField;
    private javax.swing.JLabel ppmInitLabel;
    private javax.swing.JSpinner ppmInitSpinner;
    private javax.swing.JLabel ppmLimitLabel;
    private javax.swing.JSpinner ppmLimitSpinner;
    private javax.swing.JLabel ppmOrderLabel;
    private javax.swing.JSpinner ppmOrderSpinner;
    private javax.swing.JLabel ppmStepLabel;
    private javax.swing.JSpinner ppmStepSpinner;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButton showDetailsRadioButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
